services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kartingrm
      MYSQL_USER: kartuser
      MYSQL_PASSWORD: kartpass
    volumes:
      - dbdata:/var/lib/mysql

  backend1:
    image: xsh1ft/kartingrm:latest
    restart: unless-stopped
    depends_on:
      - db
    expose:
      - "8080"
    environment:
      SPRING_MAIL_USERNAME: nicolas.sanchez.al@usach.cl
      SPRING_MAIL_PASSWORD: lflezxzzwqbwgxoa
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/kartingrm
      SPRING_DATASOURCE_USERNAME: kartuser
      SPRING_DATASOURCE_PASSWORD: kartpass

  backend2:
    image: xsh1ft/kartingrm:latest
    restart: unless-stopped
    depends_on:
      - db
    expose:
      - "8080"
    environment:
      SPRING_MAIL_USERNAME: nicolas.sanchez.al@usach.cl
      SPRING_MAIL_PASSWORD: lflezxzzwqbwgxoa
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/kartingrm
      SPRING_DATASOURCE_USERNAME: kartuser
      SPRING_DATASOURCE_PASSWORD: kartpass

  backend3:
    image: xsh1ft/kartingrm:latest
    restart: unless-stopped
    depends_on:
      - db
    expose:
      - "8080"
    environment:
      SPRING_MAIL_USERNAME: nicolas.sanchez.al@usach.cl
      SPRING_MAIL_PASSWORD: lflezxzzwqbwgxoa
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/kartingrm
      SPRING_DATASOURCE_USERNAME: kartuser
      SPRING_DATASOURCE_PASSWORD: kartpass

  nginx-backend:
    image: nginx:stable-alpine
    depends_on:
      - backend1
      - backend2
      - backend3
    volumes:
      - ./nginx-backend.conf:/etc/nginx/conf.d/default.conf:ro
    expose:
      - "80"

  frontend1:
    image: xsh1ft/kartingrm-frontend:latest
    depends_on:
      - nginx-backend
    expose:
      - "80"

  frontend2:
    image: xsh1ft/kartingrm-frontend:latest
    depends_on:
      - nginx-backend
    expose:
      - "80"

  frontend3:
    image: xsh1ft/kartingrm-frontend:latest
    depends_on:
      - nginx-backend
    expose:
      - "80"

  nginx-frontend:
    image: nginx:stable-alpine
    depends_on:
      - nginx-backend
      - frontend1
      - frontend2
      - frontend3
    volumes:
      - ./nginx-gateway.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8070:80"

volumes:
  dbdata:
